#!/bin/bash

# Compile the SID Menu
../../BeebASM/beebasm/beebasm -i menu.asm

n=1

for i in \
"http://stardot.org.uk/forums/download/file.php?id=1166" \
"http://stardot.org.uk/forums/download/file.php?id=1301" \
"http://stardot.org.uk/forums/download/file.php?id=1356" \
"http://stardot.org.uk/forums/download/file.php?id=1401" \
"http://stardot.org.uk/forums/download/file.php?id=1443" \
"http://stardot.org.uk/forums/download/file.php?id=1597" \
"http://stardot.org.uk/forums/download/file.php?id=1855" \
"http://stardot.org.uk/forums/download/file.php?id=2844" \
"http://stardot.org.uk/forums/download/file.php?id=3157" \
"http://stardot.org.uk/forums/download/file.php?id=4166" \
"http://stardot.org.uk/forums/download/file.php?id=5391" \
"http://stardot.org.uk/forums/download/file.php?id=6242" \
"http://stardot.org.uk/forums/download/file.php?id=9282" \
"http://stardot.org.uk/forums/download/file.php?id=12049" \
"http://www.stardot.org.uk/forums/download/file.php?id=16496" \
"http://www.stardot.org.uk/forums/download/file.php?id=20234" \
"http://www.stardot.org.uk/forums/download/file.php?id=26437" \
"http://www.stardot.org.uk/forums/download/file.php?id=33456"
do
 # Grab the zipped SSD from StartDot
 wget -O tmp.zip $i
 file=`unzip -ql tmp.zip | head -3 | tail -1 | awk '{print $4}'`
 unzip tmp.zip $file
 mv *.ssd tmp.ssd

 # Extract the fines
 rm -rf BEEBSID$n
 perl mmb_utils/getfile.pl tmp.ssd  BEEBSID$n

 # Work out the menu program from !BOOR
 sidmenu=`strings BEEBSID$n/\!BOOT | grep -v BASIC | sed -e "s/RUN //" | tr -d '*'`

 # Convert to AtomSID

 rm -rf ATMSID$n
 java -jar ../java/atomsid/atomsid.jar BEEBSID$n/$sidmenu SIDMENU blacklist.txt ATMSID$n 2800

 rm -f tmp.ssd tmp.zip
 n=$(( $n + 1 ))
done

zip -qr ~/ATMSID.zip ATMSID*
