  1 REM ..BUZZ-PHRASES.. 
 10 DIM S(128);W=31
 20 FOR I=100 TO 400 STEP 100
 30 GOSUB (10*(ABSRND%10)+I) 
 40 GOSUB p;NEXT; PRINT "."'
 50 LINK #FFE3; GOTO 20
 80pC=S; DO A=0; DO A=A+1; UNTIL C?A=CH" "
 82 C?A=CH""; IF COUNT+LENC>=W PRINT '
 84 PRINT $C," ";C=C+LENC+1
 86 UNTIL ?C=CH""
 88 RETURN
100 $S="IN PARTICULAR, "; RETURN
110 $S="ON THE OTHER HAND, "; RETURN
120 $S="HOWEVER, "; RETURN
130 $S="SIMILARLY, "; RETURN
140 $S="AS A RESULTANT IMPLICATION, "; RETURN
150 $S="IN THIS REGARD, "; RETURN
160 $S="BASED ON INTEGRAL SUBSYSTEM CONSIDERATIONS, "; RETURN
170 $S="FOR EXAMPLE, "; RETURN
180 $S="THUS, "; RETURN
190 $S="IN RESPECT TO SPECIFIC GOALS, "; RETURN
200 $S="A LARGE PORTION OF THE INTERFACE COORDINATION"
201 $S+LENS=" COMNUNICATION "; RETURN 
210 $S="A CONSTANT FLOW OF EFFECTIVE INFORMATION "; RETURN
220 $S="THE CHARACTERISATION OF SPECIFIC CRITERIA "; RETURN
230 $S="INITIATION OF CRITICAL SUBSYSTEN DEVELOPMENT "; RETURN
240 $S="THE FULLY INTEGRATED TEST PROGRAM "; RETURN
250 $S="THE PRODUCT CONFIGURATION BASELINE "; RETURN
260 $S="ANY ASSOCIATED SUPPORTING ELEMENT "; RETURN
270 $S="THE INCORPORATION OF ADDITIONAL"
271 $S+LENS=" MISSION CONSTRAINTS "; RETURN
280 $S="THE INDEPENDENT FUNCTIONAL PRINCIPAL "; RETURN
290 $S="A PRIMARY RELATIONSHIP BETWEEN"
291 $S+LENS=" SYSTEM AND/OR SUBSYSTEM TECHNOLOGIES "; RETURN
300 $S="MUST UTILISE AND BE FUNCTIONALLY INTERWOVEN WITH "; RETURN
310 $S="MAXIMIZES THE PROBABILITY OF PROJECT SUCCESS AND"
311 $S+LENS=" MINIMIZES THE COST AND TIME REQUIRED FOR "; RETURN
320 $S="ADDS SPECIFIC PERFORMANCE LIMITS TO "; RETURN
330 $S="NECESSITATES THAT URGENT"
331 $S+LENS=" CONSIDERATION BE APPLIED TO "; RETURN
340 $S="REQUIRES CONSIDERABLE SYSTEMS ANALYSIS AND TRADE-OFF"
341 $S+LENS=" STUDIES TO ARRIVE AT "; RETURN
350 $S="IS FURTHER COMPOUNDED, WHEN TAKING INTO ACCOUNT "; RETURN
360 $S="PRESENTS EXTRENELY INTERESTING CHALLENGES TO "; RETURN
370 $S="RECOGNISES THE IMPORTANCE OF OTHER SYSTEMS AND THE"
371 $S+LENS=" NECESSITY FOR "; RETURN
380 $S="EFFECTS A SIGNIFICANT IMPLEMENTATION OF "; RETURN
390 $S="ADDS OVERRIDING PERFORMANCE CONSTRAINTS TO "; RETURN
400 $S="THE SOPHISTICATED HARDWARE "; RETURN
410 $S="THE ANTICIPATED FOURTH GENERATION EQUIPMENT "; RETURN
420 $S="THE SUBSYSTEM COMPATIBILITY TESTING "; RETURN
430 $S="THE STRUCTURAL DESIGN, BASED ON SYSTEM ENGINEERING"
431 $S+LENS=" CONCEPTS "; RETURN
440 $S="THE PRELIMINARY QUALIFICATION LIMIT "; RETURN
450 $S="THE EVOLUTION OF SPECIFICATIONS OVER A GIVEN TIME"
451 $S+LENS=" PERIOD "; RETURN
460 $S="THE PHILOSOPHY OF COMMONALITY AND"
461 $S+LENS=" STANDARDISATION "; RETURN
470 $S="THE GREATER FIGHT-WORTHINESS CONCEPT "; RETURN
480 $S="ANY DISCRETE CONFIGURATION MODE "; RETURN
490 $S="THE TOTAL SYSTEM RATIONALE "; RETURN
