    10 REM AGD TITLEVIEWER
    20 *NOMON
    30 P.$12;?#E1=0
    40 P."     AGD TITLE VIEWER  V1.0";GOS.a
    50 P.''" THIS  PROGRAM SHOWS  THE TITLE"'
    60 P." SCREENS OF MANY AGD GAMES."'
    70 P." THE SCREENS ARE ALL CONVERTED "'
    80 P." FROM THE ZX SPECTRUM."''
    90 P." A LOT OF PEOPLE  DID PUT A LOT"'
   100 P." OF  EFFORT IN  CREATING  THESE"'
   110 P." SCREENS, LEAN BACK  AND ENJOY "'
   120 P." WATCHING ......."''
   130 P."   EVERY SCREEN IS SHOWN 2 SEC"'''
   140 P."   PRESS A KEY TO START .....";GOS.a
   150 LI.#FFE3
   160 *RUN SHOW2
   170aL=!#DE & #FFFF
   180 FOR I=0 TO 31;I?L=I?L:#80;NEXT
   190 R.
